spring:
  application.name: recommendations
security.basic.enabled: false
netflix:
  appinfo.name: ${spring.application.name}
  atlas.uri: http://localhost:7101/api/v1/publish
eureka.client.serviceUrl.defaultZone: http://localhost:9000/eureka/
server.port: 8001
endpoints.health.sensitive: false
membership.ribbon.DeploymentContextBasedVipAddresses: membership